import { defineConfig } from 'vitest/config';
import react from '@vitejs/plugin-react';
import mdx from '@mdx-js/rollup';
import remarkFrontmatter from 'remark-frontmatter';
import remarkMdxFrontmatter from 'remark-mdx-frontmatter';
import rehypeSlug from 'rehype-slug';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { existsSync, readFileSync, readdirSync } from 'node:fs';

const __dirname = dirname(fileURLToPath(import.meta.url));

/**
 * Auto-discover blog post HTML entries generated by
 * `scripts/build-blog-routes.mjs` (run via prebuild). Each generated file
 * lives at blog/<slug>.html and gets a vite input keyed `blog-<slug>`.
 *
 * If the blog/ directory doesn't exist (fresh checkout, no prebuild yet),
 * we return an empty object — the build still runs, just without per-post
 * HTML entries until the next prebuild.
 */
function discoverBlogPostEntries(): Record<string, string> {
  if (!blogIsLive()) return {};
  const blogDir = resolve(__dirname, 'blog');
  if (!existsSync(blogDir)) return {};
  const entries: Record<string, string> = {};
  for (const file of readdirSync(blogDir)) {
    if (!file.endsWith('.html')) continue;
    const slug = file.replace(/\.html$/, '');
    entries[`blog-${slug}`] = resolve(blogDir, file);
  }
  return entries;
}

function blogIsLive(): boolean {
  const readinessPath = resolve(__dirname, 'src', 'data', 'liveReadiness.json');
  if (!existsSync(readinessPath)) return false;
  const flags = JSON.parse(readFileSync(readinessPath, 'utf8')) as {
    showBlog?: boolean;
  };
  return flags.showBlog === true;
}

function blogIndexEntry(): Record<string, string> {
  if (!blogIsLive()) return {};
  return { blog: resolve(__dirname, 'blog.html') };
}

export default defineConfig({
  plugins: [
    // MDX must run BEFORE the react plugin (per @mdx-js/rollup docs) so
    // .mdx files are compiled to JSX before React's transform sees them.
    {
      enforce: 'pre',
      ...mdx({
        remarkPlugins: [remarkFrontmatter, remarkMdxFrontmatter],
        rehypePlugins: [rehypeSlug],
        // Output JSX, not function calls — lets the React plugin handle
        // the final transform with its usual hooks (Fast Refresh etc.).
        jsxImportSource: 'react',
        providerImportSource: undefined,
      }),
    },
    react({ include: /\.(jsx|tsx|mdx)$/ }),
  ],
  build: {
    outDir: 'dist',
    assetsDir: 'assets',
    sourcemap: false,
    rollupOptions: {
      input: {
        main: resolve(__dirname, 'index.html'),
        // Hurricane uplift sim deferred — excluded from production builds
        // so dist/ doesn't ship the page. Source intact at
        // /hurricane-uplift.html + /src/HurricaneUpliftPage.tsx +
        // /src/components/WindUpliftVisualizer/. To restore: uncomment
        // the line below + restore the sitemap entry + re-add the Nav
        // link in src/sections/Nav.tsx.
        // hurricane: resolve(__dirname, 'hurricane-uplift.html'),

        // Per-city service-area landing pages. Each gets its own static
        // HTML entry so per-city <head> meta (title, canonical, OG, schema)
        // is server-side and crawler-friendly. The shared React runtime
        // is loaded by /src/pages/city-mount.tsx.
        'orlando-roofing': resolve(__dirname, 'orlando-roofing.html'),
        'winter-park-roofing': resolve(__dirname, 'winter-park-roofing.html'),
        'oviedo-roofing': resolve(__dirname, 'oviedo-roofing.html'),
        'oviedo-storm-damage': resolve(__dirname, 'oviedo-storm-damage.html'),

        // Blog index + per-post HTML stay out of production builds until
        // src/data/liveReadiness.json marks the blog ready.
        ...blogIndexEntry(),
        ...discoverBlogPostEntries(),
      },
    },
  },
  test: {
    environment: 'node',
    include: [
      'src/**/*.test.ts',
      'src/**/*.test.tsx',
      'api/**/*.test.ts',
    ],
    coverage: {
      include: ['src/physics/**', 'src/data/**', 'api/_lib/**'],
      reporter: ['text', 'html'],
    },
  },
});
