import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import BlogIndex from './BlogIndex';
import BlogPost from './BlogPost';
import { getPostBySlug } from '../data/blog';
import { reportWebVitals } from '../lib/webVitals';
import { installGlobalErrorHandlers } from '../lib/globalErrors';
import '../styles/index.css';

// Tier 7 — wire the global error handler before React mounts.
installGlobalErrorHandlers();

/**
 * blog-mount — generic entrypoint shared by every blog HTML file.
 *
 * Routing modes:
 *   - data-blog-index="true" → render BlogIndex
 *   - data-blog-slug="<slug>" → render BlogPost for that post
 *
 * Each blog HTML file is generated by `scripts/build-blog-routes.mjs`
 * during prebuild. The index uses blog.html (hand-maintained); per-post
 * HTMLs are generated under blog/<slug>.html and live for the duration
 * of one build cycle.
 */

const root = document.getElementById('root');
if (!root) {
  throw new Error('blog-mount: #root element not found in document');
}

const isIndex = root.dataset.blogIndex === 'true';
const slug = root.dataset.blogSlug;

if (isIndex) {
  createRoot(root).render(
    <StrictMode>
      <BlogIndex />
    </StrictMode>,
  );
} else if (slug) {
  const post = getPostBySlug(slug);
  if (!post) {
    throw new Error(
      `blog-mount: no MDX post found for slug "${slug}". ` +
        'Add the post to src/content/blog/ or remove the stale HTML.',
    );
  }
  createRoot(root).render(
    <StrictMode>
      <BlogPost post={post} />
    </StrictMode>,
  );
} else {
  throw new Error(
    'blog-mount: #root must declare either data-blog-index="true" ' +
      'or data-blog-slug="<slug>".',
  );
}

// Tier 3 — Core Web Vitals telemetry on blog pages. Per-post LCP is
// the most useful blog-side metric (long-form posts with hero images
// can blow the budget if hero asset isn't optimised).
reportWebVitals();
