/**
 * PatternDefs — every <defs> entry used by RanchHouseSVG.
 *
 * Lifted out of the monolith so that pattern, gradient, symbol, marker, and
 * filter definitions can be iterated on without touching house geometry,
 * weather effects, or annotations.
 *
 * Static defs (no dynamic colour input) live as constants. Dynamic ones
 * (sky, sun, haze, wall, heatmap, rain rotation, lawn) accept props so the
 * parent retains control of palette + storm intensity.
 *
 * IDs follow the existing `rh-*` prefix so the rest of the SVG continues to
 * reference them without change.
 *
 * ════════════════════════════════════════════════════════════════════════
 * RASTERIZATION ARCHITECTURE — SVG fallback vs. artist-painted PNG layer
 * ════════════════════════════════════════════════════════════════════════
 *
 * Every <symbol> in this file is the SVG SOURCE OF TRUTH for one scene
 * element. The runtime never imports a symbol directly — instead, every
 * call site uses <SceneElement id="category/name" symbolHref="#rh-...">
 * (in Landscape.tsx + SkyAtmosphere.tsx). SceneElement consults the
 * manifest at src/data/scene-manifest.ts (auto-generated by
 * scripts/export-scene-elements.mjs) and:
 *
 *   • If a PNG is registered for that placement →
 *       renders <image href="/images/scene/category/name.png"> at full
 *       canvas. The artist's paint replaces the SVG visual.
 *
 *   • If no PNG is registered →
 *       renders <use href="#rh-..."> at the canonical position, instancing
 *       the SVG <symbol> defined here. This is the fallback.
 *
 * The check is at the <use> SITE, not inside the <symbol>, because the
 * same symbol is often instanced multiple times at different positions
 * (rh-oak appears 3× as left/right/mid trees, each potentially having a
 * different painted PNG). Putting the check inside the symbol couldn't
 * distinguish placements.
 *
 * RASTERIZABLE symbols (have manifest entries — runtime may swap to PNG):
 *   • rh-oak       → foreground/oak-tree-{left|right|mid}    (opt-in)
 *   • rh-palm      → background/palm-bg-{left|right}
 *   • rh-bush      → foreground/bush-{1..5}
 *   • rh-hibiscus  → foreground/hibiscus-{1..5}
 *   • rh-cloud     → sky/cloud-{bg|mid|near}-{1..N}
 *   • rh-treeline  → sky/treeline-{far|near}
 *
 * SVG-ONLY symbols (always rendered as SVG — DO NOT add a PNG override):
 *   • rh-bird      — frame-by-frame CSS animation; static raster would
 *                    freeze the wing flap
 *   • rh-leaf      — drives FlyingLeaves debris cloud (per-leaf RAF
 *                    transform); a PNG can't be position-animated per
 *                    instance the way the SVG instances are
 *
 * Other SVG layers that sit OUTSIDE this file but stay procedural:
 *   • Rain particles (WeatherEffects.tsx — RainSystem) — per-drop
 *     physics + splash bursts + atmospheric haze. A static PNG can't
 *     drift, drift-rate-shift with wind, or splash on impact.
 *   • Wind streamlines (WeatherEffects.tsx — WindStreamlines) —
 *     deterministic per-particle flow with mid-cycle wobble keyframes.
 *   • Roof failure cascade (RoofAssembly.tsx — tab lift, tab fly,
 *     panel fly + spin, sheathing flash, drip-edge flutter) —
 *     keyframe animations triggered by physics state.
 *   • Lightning (WeatherEffects.tsx — Lightning) — L-system bolt
 *     generated fresh per strike; position + branching are random.
 *   • Hail (WeatherEffects.tsx — Hail) — CSS-driven trajectory + the
 *     impact splash + ground crater accumulation.
 *   • Hurricane shutters (HouseStructure.tsx) — three closed-state
 *     blocks with hardware (tracks, hex bolts, mid-brace). Could
 *     theoretically be rasterized but they participate in the storm-
 *     deployment animation if it gets wired in later, so kept SVG.
 *   • Vortices, hail accumulation, ice fog, ground craters — all are
 *     intensity-gated procedural overlays that need to fade in/out
 *     based on real-time storm state.
 *
 * If you're an artist looking at this file, the rule is: only the
 * symbols labeled "RASTERIZABLE" can be replaced via PNG; everything
 * else needs to stay vector. See public/images/scene/README.md for the
 * round-trip workflow.
 */
interface Props {
  /** Sky gradient — top of canvas */
  skyTop: string;
  /** Sky gradient — mid band */
  skyMid: string;
  /** Sky gradient — horizon (also reused inside the glass reflection) */
  skyHorizon: string;
  /** 0–1 opacity for the sun radial */
  sunOpacity: number;
  /** 0–1 storm intensity — drives haze depth + rain angle */
  storm: number;
  /** Stucco wall vertical gradient — top */
  wallTop: string;
  /** Stucco wall vertical gradient — bottom */
  wallBot: string;
  /** Heatmap gradient stop at corner zones (Z3) */
  heatColorCorner: string;
  /** Heatmap gradient stop at edge zones (Z2) */
  heatColorEdge: string;
  /** Heatmap gradient stop at field zone (Z1) */
  heatColorField: string;
  /** Lawn gradient — top */
  lawnTop: string;
  /** Lawn gradient — bottom */
  lawnBot: string;
  /** Shingle palette — three tones + shadow + highlight (from RoofTone preset) */
  shingleLight: string;
  shingleMid: string;
  shingleDark: string;
  shingleShadow: string;
  shingleHighlight: string;
  /** Warm fill-light tone bouncing UP from the ground (from TOD palette) */
  ambientFill?: string;
  /** Rain intensity 0–1 — drives wet-sheen visibility */
  rainIntensity?: number;
}

export default function PatternDefs({
  skyTop,
  skyMid,
  skyHorizon,
  sunOpacity,
  storm,
  wallTop,
  wallBot,
  heatColorCorner,
  heatColorEdge,
  heatColorField,
  lawnTop,
  lawnBot,
  shingleLight,
  shingleMid,
  shingleDark,
  shingleShadow,
  shingleHighlight,
  ambientFill = 'rgba(255, 220, 165, 0.30)',
  rainIntensity = 0,
}: Props) {
  return (
    <defs>
      {/* SKY */}
      <linearGradient id="rh-sky" x1="0" y1="0" x2="0" y2="1">
        <stop offset="0%" stopColor={skyTop} />
        <stop offset="55%" stopColor={skyMid} />
        <stop offset="100%" stopColor={skyHorizon} />
      </linearGradient>

      <radialGradient id="rh-sun" cx="50%" cy="50%" r="50%">
        <stop offset="0%" stopColor={`rgba(255, 230, 180, ${0.95 * sunOpacity})`} />
        <stop offset="35%" stopColor={`rgba(255, 200, 130, ${0.4 * sunOpacity})`} />
        <stop offset="100%" stopColor="rgba(255, 200, 130, 0)" />
      </radialGradient>

      <linearGradient id="rh-haze" x1="0" y1="0" x2="0" y2="1">
        <stop offset="0%" stopColor="rgba(0,0,0,0)" />
        <stop offset="100%" stopColor={`rgba(${20 - storm * 10}, ${18 - storm * 10}, ${22 - storm * 12}, ${0.45 + storm * 0.3})`} />
      </linearGradient>

      {/* STUCCO WALL — vertical gradient + subtle texture */}
      <linearGradient id="rh-wall" x1="0" y1="0" x2="0" y2="1">
        <stop offset="0%" stopColor={wallTop} />
        <stop offset="100%" stopColor={wallBot} />
      </linearGradient>

      {/* STUCCO — denser, more dimensional speckle. Each speck has a
          paired sub-shadow offset down-right (sun upper-left) so each
          fleck reads as a tiny raised bump rather than a flat dot. */}
      <pattern id="rh-stucco" width="8" height="8" patternUnits="userSpaceOnUse">
        <rect width="8" height="8" fill="rgba(0,0,0,0)" />
        {/* Highlight + matching micro-shadow (paired = embossed pebbles) */}
        <circle cx="1.2" cy="1.5" r="0.40" fill="rgba(0,0,0,0.12)" />
        <circle cx="1.4" cy="1.7" r="0.18" fill="rgba(255,255,255,0.10)" />
        <circle cx="3.5" cy="0.8" r="0.28" fill="rgba(0,0,0,0.10)" />
        <circle cx="3.6" cy="0.95" r="0.14" fill="rgba(255,255,255,0.08)" />
        <circle cx="6.2" cy="2.3" r="0.48" fill="rgba(0,0,0,0.11)" />
        <circle cx="6.35" cy="2.45" r="0.22" fill="rgba(255,255,255,0.10)" />
        <circle cx="2.0" cy="4.5" r="0.38" fill="rgba(0,0,0,0.09)" />
        <circle cx="2.15" cy="4.65" r="0.18" fill="rgba(255,255,255,0.07)" />
        <circle cx="5.5" cy="5.2" r="0.34" fill="rgba(0,0,0,0.09)" />
        <circle cx="5.65" cy="5.35" r="0.16" fill="rgba(255,255,255,0.07)" />
        <circle cx="0.8" cy="6.8" r="0.30" fill="rgba(0,0,0,0.07)" />
        <circle cx="0.9" cy="6.92" r="0.14" fill="rgba(255,255,255,0.06)" />
        <circle cx="7.0" cy="6.5" r="0.40" fill="rgba(0,0,0,0.08)" />
        <circle cx="7.18" cy="6.65" r="0.18" fill="rgba(255,255,255,0.07)" />
        <circle cx="3.8" cy="7.2" r="0.24" fill="rgba(0,0,0,0.06)" />
        <circle cx="3.9" cy="7.32" r="0.12" fill="rgba(255,255,255,0.05)" />
        {/* Extra micro-grain (single-pixel-class flecks for depth fill) */}
        <circle cx="4.4" cy="2.6" r="0.10" fill="rgba(0,0,0,0.18)" />
        <circle cx="6.0" cy="0.4" r="0.10" fill="rgba(0,0,0,0.16)" />
        <circle cx="0.4" cy="3.0" r="0.10" fill="rgba(0,0,0,0.14)" />
        <circle cx="2.7" cy="3.5" r="0.08" fill="rgba(255,255,255,0.05)" />
        <circle cx="4.9" cy="6.6" r="0.10" fill="rgba(0,0,0,0.15)" />
      </pattern>

      {/* SIDING — subtle horizontal clapboard lines on the wall surface */}
      <pattern id="rh-siding" width="40" height="22" patternUnits="userSpaceOnUse">
        <rect width="40" height="22" fill="rgba(0,0,0,0)" />
        <line x1="0" y1="11" x2="40" y2="11" stroke="rgba(0,0,0,0.10)" strokeWidth="0.4" />
        <line x1="0" y1="11.5" x2="40" y2="11.5" stroke="rgba(255,255,255,0.04)" strokeWidth="0.3" />
      </pattern>

      {/* WINDOW glass — multi-stop reflection with cool tint and warm catchlight */}
      <linearGradient id="rh-glass" x1="0.2" y1="0" x2="0.8" y2="1">
        <stop offset="0%" stopColor={skyMid} stopOpacity="0.95" />
        <stop offset="35%" stopColor={skyHorizon} stopOpacity="0.7" />
        <stop offset="55%" stopColor="rgba(28, 32, 40, 0.85)" />
        <stop offset="100%" stopColor="rgba(20, 22, 28, 0.92)" />
      </linearGradient>

      {/* Glass diagonal sheen — applied as overlay for the wet/glossy look */}
      <linearGradient id="rh-glass-sheen" x1="0" y1="0" x2="1" y2="1">
        <stop offset="20%" stopColor="rgba(255, 255, 255, 0)" />
        <stop offset="40%" stopColor="rgba(255, 255, 255, 0.18)" />
        <stop offset="50%" stopColor="rgba(255, 255, 255, 0)" />
      </linearGradient>

      {/* ROOF lighting — pushed stronger for Phase-1 3D depth */}
      <linearGradient id="rh-roof-light" x1="0.5" y1="0" x2="0.5" y2="1">
        <stop offset="0%" stopColor={`rgba(255, 240, 200, ${0.32 * sunOpacity})`} />
        <stop offset="55%" stopColor="rgba(0, 0, 0, 0.05)" />
        <stop offset="100%" stopColor="rgba(0, 0, 0, 0.38)" />
      </linearGradient>

      {/* ════════════════ PHASE-1 QUASI-3D HELPER DEFS ════════════════
          Reusable lighting/shadow gradients applied across the scene to
          sell volumetric depth without WebGL. */}

      {/* AMBIENT-OCCLUSION — top edge. Apply over a thin strip at the
          top of any recessed area (window glass, door panel, garage door,
          porch overhang underside). Sun is upper-left → top edges of any
          recess catch a dark contact-shadow band. */}
      <linearGradient id="rh-ao-top" x1="0" y1="0" x2="0" y2="1">
        <stop offset="0%" stopColor="rgba(0, 0, 0, 0.55)" />
        <stop offset="100%" stopColor="rgba(0, 0, 0, 0)" />
      </linearGradient>

      {/* AMBIENT-OCCLUSION — left edge. Sun upper-left → left edges of
          any recess catch a softer shadow than the top edge. */}
      <linearGradient id="rh-ao-left" x1="0" y1="0" x2="1" y2="0">
        <stop offset="0%" stopColor="rgba(0, 0, 0, 0.40)" />
        <stop offset="100%" stopColor="rgba(0, 0, 0, 0)" />
      </linearGradient>

      {/* FACE-LIGHT — top-bright → bottom-dark vertical lighting overlay
          for any sun-facing flat surface. mix-blend overlay = bright tops,
          shaded bottoms = strong volumetric read on side walls, garage
          door, doors, etc. */}
      <linearGradient id="rh-face-light" x1="0" y1="0" x2="0" y2="1">
        <stop offset="0%" stopColor={`rgba(255, 240, 210, ${0.22 * sunOpacity})`} />
        <stop offset="50%" stopColor="rgba(0, 0, 0, 0)" />
        <stop offset="100%" stopColor="rgba(0, 0, 0, 0.30)" />
      </linearGradient>

      {/* SIDE-FACE shadow — flat dark gradient for receding side faces
          (right-side wall extrusions, chimney side, garage side). Top
          slightly lighter so the eye reads "this is in shadow" not "this
          is a flat black rect". */}
      <linearGradient id="rh-side-shadow" x1="0" y1="0" x2="0" y2="1">
        <stop offset="0%" stopColor="rgba(0, 0, 0, 0.35)" />
        <stop offset="100%" stopColor="rgba(0, 0, 0, 0.62)" />
      </linearGradient>

      {/* ROOF SPECULAR — narrow bright streak running parallel to the
          ridge on the sun-facing slope. Simulates sun grazing the
          asphalt granules. Applied with mix-blend-mode 'screen'. */}
      <linearGradient id="rh-roof-specular" x1="0.5" y1="0" x2="0.5" y2="1">
        <stop offset="0%" stopColor="rgba(255, 248, 220, 0)" />
        <stop offset="14%" stopColor={`rgba(255, 248, 220, ${0.42 * sunOpacity})`} />
        <stop offset="22%" stopColor="rgba(255, 248, 220, 0)" />
        <stop offset="100%" stopColor="rgba(0, 0, 0, 0)" />
      </linearGradient>

      {/* CONTACT SHADOW — soft elliptical drop-shadow used under mailbox,
          chimney, palms, etc. Radial from black-center to transparent. */}
      <radialGradient id="rh-contact-shadow" cx="50%" cy="50%" r="50%">
        <stop offset="0%" stopColor="rgba(0, 0, 0, 0.55)" />
        <stop offset="60%" stopColor="rgba(0, 0, 0, 0.18)" />
        <stop offset="100%" stopColor="rgba(0, 0, 0, 0)" />
      </radialGradient>

      {/* REFLECTED FILL LIGHT — warm bounce from the lawn UP onto walls,
          chimney face, and the underside of the door overhang. Strongest
          near the ground (foundation), fading to nothing mid-wall.
          Dramatically sells the "outdoor scene with a real ground" feel. */}
      <linearGradient id="rh-fill-light" x1="0" y1="1" x2="0" y2="0">
        <stop offset="0%" stopColor={ambientFill} />
        <stop offset="55%" stopColor="rgba(0, 0, 0, 0)" />
        <stop offset="100%" stopColor="rgba(0, 0, 0, 0)" />
      </linearGradient>

      {/* ATMOSPHERIC HAZE — bluish overlay applied to distant background
          elements. Sells aerial perspective: "this thing is far away,
          the air between you and it has color." */}
      <linearGradient id="rh-atmosphere" x1="0" y1="0" x2="0" y2="1">
        <stop offset="0%" stopColor="rgba(140, 170, 200, 0.18)" />
        <stop offset="100%" stopColor="rgba(180, 200, 220, 0.30)" />
      </linearGradient>

      {/* WET-SURFACE SHEEN — diagonal specular streak applied to lawn,
          pavers, walkway, and roof during rain. Modulates by rainIntensity
          so it appears progressively as the storm escalates. */}
      <linearGradient
        id="rh-wet-sheen"
        x1="0" y1="0" x2="1" y2="1"
      >
        <stop offset="20%" stopColor="rgba(255, 255, 255, 0)" />
        <stop offset="48%" stopColor={`rgba(180, 210, 235, ${(rainIntensity * 0.32).toFixed(2)})`} />
        <stop offset="55%" stopColor={`rgba(220, 240, 255, ${(rainIntensity * 0.42).toFixed(2)})`} />
        <stop offset="62%" stopColor={`rgba(180, 210, 235, ${(rainIntensity * 0.32).toFixed(2)})`} />
        <stop offset="90%" stopColor="rgba(255, 255, 255, 0)" />
      </linearGradient>

      {/* SOFFIT — repeating ribbed pattern for the underside of eaves.
          Reads as physical aluminum/vinyl soffit panels, big depth cue. */}
      <pattern id="rh-soffit" width="14" height="6" patternUnits="userSpaceOnUse">
        <rect width="14" height="6" fill="#1a1612" />
        <line x1="3.5" y1="0" x2="3.5" y2="6" stroke="rgba(0,0,0,0.55)" strokeWidth="0.5" />
        <line x1="10.5" y1="0" x2="10.5" y2="6" stroke="rgba(0,0,0,0.55)" strokeWidth="0.5" />
        <line x1="4.0" y1="0" x2="4.0" y2="6" stroke="rgba(255,255,255,0.06)" strokeWidth="0.3" />
        <line x1="11.0" y1="0" x2="11.0" y2="6" stroke="rgba(255,255,255,0.06)" strokeWidth="0.3" />
      </pattern>

      {/* INTERIOR GLOW — warm window light spilling out at dusk/night. */}
      <radialGradient id="rh-interior-glow" cx="50%" cy="50%" r="50%">
        <stop offset="0%" stopColor="rgba(255, 220, 150, 1)" />
        <stop offset="40%" stopColor="rgba(255, 200, 120, 0.85)" />
        <stop offset="100%" stopColor="rgba(255, 180, 90, 0)" />
      </radialGradient>

      {/* WIND STREAK — gradient stroke for the particle-system wind.
          Tail fully transparent → head soft, never fully opaque. Earlier
          1.0-alpha head produced bright dots at random Y positions when
          the particles wobbled, reading as glitchy scratches against the
          dark storm sky. Capping the head at 0.55 keeps each particle as
          a true motion-blur whisper. */}
      <linearGradient id="rh-wind-streak" x1="0" y1="0" x2="1" y2="0">
        <stop offset="0%"  stopColor="rgba(228, 236, 246, 0)" />
        <stop offset="60%" stopColor="rgba(228, 236, 246, 0.18)" />
        <stop offset="100%" stopColor="rgba(245, 250, 255, 0.55)" />
      </linearGradient>

      {/* WIND BURST — occasional brighter "gust" streaks. Same softening
          principle: head capped at 0.78 so the eye reads acceleration,
          not a solid pixel. */}
      <linearGradient id="rh-wind-burst" x1="0" y1="0" x2="1" y2="0">
        <stop offset="0%"  stopColor="rgba(255, 250, 230, 0)" />
        <stop offset="60%" stopColor="rgba(255, 245, 215, 0.32)" />
        <stop offset="100%" stopColor="rgba(255, 252, 240, 0.78)" />
      </linearGradient>

      {/* RAIN STREAK — motion-blur gradient for foreground hero drops.
          Real rain photographed at fast shutter shows a transparent tail
          where the drop entered the frame and a brighter head where it
          currently is — that asymmetry is what reads as motion to the
          eye. Tail fully transparent → head bright. The line is drawn
          along the wind-tilted vector so the gradient direction follows
          the trajectory naturally. */}
      <linearGradient id="rh-rain-streak" x1="0" y1="0" x2="1" y2="1" gradientUnits="objectBoundingBox">
        <stop offset="0%"   stopColor="rgba(220, 235, 252, 0)" />
        <stop offset="35%"  stopColor="rgba(232, 244, 255, 0.35)" />
        <stop offset="80%"  stopColor="rgba(245, 252, 255, 0.85)" />
        <stop offset="100%" stopColor="rgba(255, 255, 255, 0.95)" />
      </linearGradient>

      {/* RAIN HAZE — atmospheric veil that softens the mid-distance during
          heavy rain. Real downpours desaturate the background as the air
          column fills with water droplets scattering light. Linear top→
          bottom: transparent at the horizon, slightly cool-tinted at the
          ground line. Applied as a screen-blended overlay only at high
          intensity. */}
      <linearGradient id="rh-rain-haze-grad" x1="0" y1="0" x2="0" y2="1">
        <stop offset="0%"   stopColor="rgba(190, 215, 235, 0)" />
        <stop offset="55%"  stopColor="rgba(195, 220, 240, 0.10)" />
        <stop offset="100%" stopColor="rgba(205, 228, 245, 0.22)" />
      </linearGradient>

      {/* MOON craters — applied as pattern on the moon at night. */}
      <radialGradient id="rh-moon-surface" cx="42%" cy="38%" r="60%">
        <stop offset="0%" stopColor="rgba(248, 250, 255, 1)" />
        <stop offset="55%" stopColor="rgba(220, 228, 245, 1)" />
        <stop offset="100%" stopColor="rgba(180, 195, 222, 1)" />
      </radialGradient>

      {/* SHINGLES — staggered tab pattern, pushed 3D depth.
          Now per tab: a dark inset shadow on the LEFT edge (sun upper-left),
          a brighter top-edge highlight, an embossed lower drop-shadow,
          AND 12 grain flecks instead of 6 for tactile granular feel. */}
      <pattern id="rh-shingles" width="48" height="12" patternUnits="userSpaceOnUse">
        {/* Shadow row underneath (the next course peeking through) */}
        <rect width="48" height="12" fill={shingleDark} />
        {/* Main course tabs — three slightly varying tones */}
        <rect x="0"  y="0" width="16" height="8" fill={shingleLight} />
        <rect x="16" y="0" width="16" height="8" fill={shingleMid} />
        <rect x="32" y="0" width="16" height="8" fill={shingleLight} />
        {/* Per-tab LEFT-edge inset shadow (sun is upper-left, so the
            inside of the tab seam catches deep shadow) */}
        <rect x="0"  y="0" width="1.2" height="8" fill="rgba(0,0,0,0.30)" />
        <rect x="16" y="0" width="1.2" height="8" fill="rgba(0,0,0,0.30)" />
        <rect x="32" y="0" width="1.2" height="8" fill="rgba(0,0,0,0.30)" />
        {/* Per-tab RIGHT-edge mini highlight */}
        <rect x="14.7" y="0" width="0.5" height="8" fill="rgba(255,235,200,0.10)" />
        <rect x="30.7" y="0" width="0.5" height="8" fill="rgba(255,235,200,0.10)" />
        <rect x="46.7" y="0" width="0.5" height="8" fill="rgba(255,235,200,0.10)" />
        {/* Tab separators (vertical kerf lines) */}
        <line x1="16" y1="0" x2="16" y2="8" stroke={shingleShadow} strokeWidth="0.55" />
        <line x1="32" y1="0" x2="32" y2="8" stroke={shingleShadow} strokeWidth="0.55" />
        {/* Embossed cast-shadow band — tab thickness reading downward */}
        <rect x="0" y="7.4" width="48" height="0.8" fill="rgba(0,0,0,0.55)" />
        <rect x="0" y="8.2" width="48" height="2"  fill="rgba(0,0,0,0.30)" />
        <rect x="0" y="10.2" width="48" height="1.5" fill="rgba(0,0,0,0.16)" />
        {/* Top-edge highlight catching the light */}
        <line x1="0" y1="0.5" x2="48" y2="0.5" stroke={shingleHighlight} strokeWidth="0.5" />
        {/* Granular texture flecks — denser, varied sizes */}
        <circle cx="2.4"  cy="2.5" r="0.30" fill="rgba(255,255,255,0.10)" />
        <circle cx="5.7"  cy="5.2" r="0.22" fill="rgba(0,0,0,0.22)" />
        <circle cx="9.1"  cy="3.4" r="0.18" fill="rgba(255,255,255,0.07)" />
        <circle cx="12.3" cy="6.0" r="0.26" fill="rgba(0,0,0,0.18)" />
        <circle cx="18.4" cy="2.0" r="0.28" fill="rgba(255,255,255,0.08)" />
        <circle cx="21.6" cy="5.5" r="0.20" fill="rgba(0,0,0,0.20)" />
        <circle cx="25.0" cy="3.0" r="0.24" fill="rgba(255,255,255,0.09)" />
        <circle cx="28.4" cy="6.4" r="0.22" fill="rgba(0,0,0,0.18)" />
        <circle cx="34.5" cy="2.6" r="0.26" fill="rgba(255,255,255,0.10)" />
        <circle cx="37.8" cy="5.8" r="0.20" fill="rgba(0,0,0,0.20)" />
        <circle cx="41.6" cy="3.2" r="0.18" fill="rgba(255,255,255,0.07)" />
        <circle cx="44.9" cy="6.0" r="0.24" fill="rgba(0,0,0,0.18)" />
      </pattern>

      {/* SHEATHING — OSB strand-board texture (oriented chips with grain) */}
      <pattern id="rh-sheathing-pat" width="48" height="32" patternUnits="userSpaceOnUse">
        <rect width="48" height="32" fill="#6b5840" />
        {/* Random oriented strands — the OSB look */}
        <rect x="2"  y="3"  width="14" height="3" fill="#564228" transform="rotate(8 9 4.5)" />
        <rect x="20" y="2"  width="18" height="2.5" fill="#7a6448" transform="rotate(-4 29 3.25)" />
        <rect x="4"  y="9"  width="12" height="2.8" fill="#4a3820" transform="rotate(-6 10 10.4)" />
        <rect x="22" y="10" width="20" height="3" fill="#5e4a30" transform="rotate(3 32 11.5)" />
        <rect x="3"  y="16" width="16" height="2.5" fill="#7a6448" transform="rotate(5 11 17.25)" />
        <rect x="24" y="17" width="14" height="3" fill="#4a3820" transform="rotate(-3 31 18.5)" />
        <rect x="6"  y="24" width="18" height="2.8" fill="#5e4a30" transform="rotate(-2 15 25.4)" />
        <rect x="28" y="25" width="14" height="3" fill="#7a6448" transform="rotate(7 35 26.5)" />
        {/* Panel edge separator (horizontal) */}
        <line x1="0" y1="16" x2="48" y2="16" stroke="#2c2014" strokeWidth="0.35" opacity="0.5" />
      </pattern>

      <pattern id="rh-swb-pat" width="8" height="8" patternUnits="userSpaceOnUse">
        <rect width="8" height="8" fill="#4a3526" />
        <circle cx="4" cy="4" r="0.6" fill="#eb6924" opacity="0.5" />
      </pattern>

      {/* CHIMNEY BRICK — running-bond brick pattern with recessed mortar
          joints + per-brick bevel (top highlight, bottom shadow, left
          inset). Each brick reads as physically raised. */}
      <pattern id="rh-chimney-brick" width="11" height="6" patternUnits="userSpaceOnUse">
        {/* Mortar base (the recessed joint color) */}
        <rect width="11" height="6" fill="#2a1f17" />
        {/* Brick body — slightly varying tones across the two staggered rows */}
        <rect x="0.5" y="0.5" width="10" height="2.4" fill="#5e3922" />
        {/* Running bond — second row offset by half */}
        <rect x="-4.5" y="3.2" width="5"  height="2.4" fill="#6a4128" />
        <rect x="0.7"  y="3.2" width="5"  height="2.4" fill="#62391f" />
        <rect x="6.0"  y="3.2" width="5"  height="2.4" fill="#6a4128" />
        {/* Top-edge highlight on each brick (sun upper-left) */}
        <line x1="0.5" y1="0.6" x2="10.5" y2="0.6" stroke="rgba(255, 220, 180, 0.18)" strokeWidth="0.25" />
        <line x1="0.7" y1="3.3" x2="5.7"  y2="3.3" stroke="rgba(255, 220, 180, 0.18)" strokeWidth="0.25" />
        <line x1="6.0" y1="3.3" x2="11.0" y2="3.3" stroke="rgba(255, 220, 180, 0.18)" strokeWidth="0.25" />
        {/* Bottom-edge shadow (cast onto mortar below) */}
        <line x1="0.5" y1="2.85" x2="10.5" y2="2.85" stroke="rgba(0, 0, 0, 0.45)" strokeWidth="0.30" />
        <line x1="0.7" y1="5.55" x2="5.7"  y2="5.55" stroke="rgba(0, 0, 0, 0.45)" strokeWidth="0.30" />
        <line x1="6.0" y1="5.55" x2="11.0" y2="5.55" stroke="rgba(0, 0, 0, 0.45)" strokeWidth="0.30" />
        {/* Left-edge inset shadow on each brick (sun upper-left) */}
        <rect x="0.5" y="0.6"  width="0.4" height="2.3" fill="rgba(0, 0, 0, 0.20)" />
        <rect x="0.7" y="3.3"  width="0.4" height="2.3" fill="rgba(0, 0, 0, 0.20)" />
        <rect x="6.0" y="3.3"  width="0.4" height="2.3" fill="rgba(0, 0, 0, 0.20)" />
        {/* Brick speckle for old-brick texture */}
        <circle cx="3"   cy="1.5" r="0.18" fill="rgba(0, 0, 0, 0.20)" />
        <circle cx="7"   cy="2.0" r="0.14" fill="rgba(255, 220, 180, 0.10)" />
        <circle cx="2.5" cy="4.5" r="0.16" fill="rgba(0, 0, 0, 0.18)" />
        <circle cx="8"   cy="4.2" r="0.14" fill="rgba(0, 0, 0, 0.18)" />
      </pattern>

      {/* CMU CONCRETE BLOCK — running-bond pattern that overlays the wall.
          Matches Sandra's actual house at 2703 Dobbin: CMU (concrete masonry
          unit) construction is the dominant residential build for Central
          FL ranches because it's hurricane-rated. Real blocks are 8"×16".
          At our scale → 22×11 pattern with subtle mortar joints + block
          highlight/shadow per course. Applied at low opacity so it reads
          as the underlying wall structure under the stucco finish. */}
      <pattern id="rh-cmu-block" width="22" height="11" patternUnits="userSpaceOnUse">
        <rect width="22" height="11" fill="rgba(0,0,0,0)" />
        {/* Horizontal mortar joints (top of each course) */}
        <line x1="0" y1="0.4" x2="22" y2="0.4" stroke="rgba(0,0,0,0.30)" strokeWidth="0.5" />
        <line x1="0" y1="5.5" x2="22" y2="5.5" stroke="rgba(0,0,0,0.30)" strokeWidth="0.5" />
        {/* Sun-catch highlight on top of each block (sun upper-left) */}
        <line x1="0" y1="0.95" x2="22" y2="0.95" stroke="rgba(255,240,210,0.20)" strokeWidth="0.4" />
        <line x1="0" y1="6.05" x2="22" y2="6.05" stroke="rgba(255,240,210,0.20)" strokeWidth="0.4" />
        {/* Vertical mortar joints — RUNNING BOND (top row joint at x=0,
            bottom row offset by half = x=11). This is the textbook CMU
            stagger that prevents continuous vertical joints. */}
        <line x1="0"  y1="0"   x2="0"  y2="5.5" stroke="rgba(0,0,0,0.30)" strokeWidth="0.5" />
        <line x1="22" y1="0"   x2="22" y2="5.5" stroke="rgba(0,0,0,0.30)" strokeWidth="0.5" />
        <line x1="11" y1="5.5" x2="11" y2="11"  stroke="rgba(0,0,0,0.30)" strokeWidth="0.5" />
        {/* Vertical highlight on right side of each block (sun glances off) */}
        <line x1="0.6"  y1="0.9" x2="0.6"  y2="5.4" stroke="rgba(255,240,210,0.15)" strokeWidth="0.3" />
        <line x1="11.6" y1="6.0" x2="11.6" y2="10.9" stroke="rgba(255,240,210,0.15)" strokeWidth="0.3" />
        {/* Subtle aggregate flecks per block — looks like real cast block */}
        <circle cx="5"  cy="3"   r="0.20" fill="rgba(255,255,255,0.10)" />
        <circle cx="14" cy="2.2" r="0.18" fill="rgba(0,0,0,0.20)" />
        <circle cx="18" cy="4"   r="0.20" fill="rgba(255,255,255,0.10)" />
        <circle cx="3"  cy="8"   r="0.20" fill="rgba(0,0,0,0.18)" />
        <circle cx="13" cy="9"   r="0.16" fill="rgba(255,255,255,0.09)" />
        <circle cx="19" cy="7.5" r="0.20" fill="rgba(0,0,0,0.20)" />
      </pattern>

      {/* BOARD-AND-BATTEN — vertical siding pattern for the accent gable
          above the garage. A common Florida ranch architectural detail:
          wide cream-painted boards with thin dark batten strips covering
          the seams between them. Each batten gets a left-edge sun
          highlight + right-edge shadow so it reads as a raised wood
          strip standing proud of the boards. */}
      <pattern id="rh-board-batten" width="8" height="40" patternUnits="userSpaceOnUse">
        {/* Board face (warm cream, matches the trim palette) */}
        <rect width="8" height="40" fill="#e8dfc4" />
        {/* Batten cap — narrow dark vertical strip covering the joint */}
        <rect x="0" y="0" width="2.4" height="40" fill="#7a6b50" />
        {/* Batten bevel — left highlight (sun upper-left) */}
        <line x1="0.4" y1="0" x2="0.4" y2="40" stroke="rgba(255,240,200,0.45)" strokeWidth="0.4" />
        {/* Batten bevel — right shadow (cast onto board behind) */}
        <line x1="2.1" y1="0" x2="2.1" y2="40" stroke="rgba(0,0,0,0.50)" strokeWidth="0.5" />
        {/* Board right-edge shadow against next batten */}
        <line x1="7.6" y1="0" x2="7.6" y2="40" stroke="rgba(0,0,0,0.18)" strokeWidth="0.3" />
        {/* Subtle horizontal weather-grooves in the boards — gives wood
            its characteristic horizontal grain reading */}
        <line x1="2.4" y1="6"  x2="8" y2="6"  stroke="rgba(0,0,0,0.07)"   strokeWidth="0.3" />
        <line x1="2.4" y1="14" x2="8" y2="14" stroke="rgba(255,255,255,0.10)" strokeWidth="0.3" />
        <line x1="2.4" y1="22" x2="8" y2="22" stroke="rgba(0,0,0,0.07)"   strokeWidth="0.3" />
        <line x1="2.4" y1="30" x2="8" y2="30" stroke="rgba(255,255,255,0.10)" strokeWidth="0.3" />
      </pattern>

      {/* SHUTTER LOUVER — beveled tile that turns the flat shutter rects
          into proper louver panels. Each pattern repeat = one louver:
            - sun-catch highlight on the leading top edge
            - left-edge highlight (sun upper-left)
            - dark recess band at the bottom (the gap between louvers)
            - inner shadow + far-side highlight inside the recess so the
              gap reads as 3-dimensional, not just a dark line.
          Applied as fill on every open + closed shutter rect — replaces
          the previous manual slat lines with a true louvered look. */}
      <pattern id="rh-shutter-louver" width="12" height="18" patternUnits="userSpaceOnUse">
        {/* Louver face (the flat slat surface) */}
        <rect width="12" height="18" fill="#5b4f44" />
        {/* Sun-catch highlight on louver leading edge */}
        <line x1="0" y1="0.5" x2="12" y2="0.5" stroke="rgba(255, 230, 180, 0.42)" strokeWidth="0.5" />
        {/* Left-edge sun rim (sun upper-left grazes the slat's left tip) */}
        <line x1="0.4" y1="0" x2="0.4" y2="14" stroke="rgba(255, 230, 180, 0.20)" strokeWidth="0.3" />
        {/* Right-edge inset shadow (slat's far side falls in shadow) */}
        <line x1="11.6" y1="0" x2="11.6" y2="14" stroke="rgba(0, 0, 0, 0.30)" strokeWidth="0.3" />
        {/* Bottom shadow line (where louver face meets the recess gap) */}
        <line x1="0" y1="13.7" x2="12" y2="13.7" stroke="rgba(0, 0, 0, 0.65)" strokeWidth="0.6" />
        {/* Recess gap (the dark band between louvers) */}
        <rect x="0" y="14" width="12" height="3" fill="#2c241c" />
        {/* Inner cast shadow (deeper darkness inside the recess from the
            louver above) */}
        <line x1="0" y1="14.4" x2="12" y2="14.4" stroke="rgba(0, 0, 0, 0.55)" strokeWidth="0.4" />
        {/* Far-side highlight (the next louver's leading edge peeking
            through the recess — completes the 3D louver illusion) */}
        <line x1="0" y1="17.5" x2="12" y2="17.5" stroke="rgba(255, 220, 170, 0.28)" strokeWidth="0.4" />
      </pattern>

      {/* HEATMAP gradient */}
      <linearGradient id="rh-heat" x1="0" y1="0" x2="1" y2="0">
        <stop offset="0%" stopColor={heatColorCorner} />
        <stop offset="20%" stopColor={heatColorEdge} />
        <stop offset="50%" stopColor={heatColorField} />
        <stop offset="80%" stopColor={heatColorEdge} />
        <stop offset="100%" stopColor={heatColorCorner} />
      </linearGradient>

      {/* ┌── RASTERIZABLE ──────────────────────────────────────────────┐
          │ rh-cloud → manifest keys sky/cloud-{bg|mid|near}-{1..N}      │
          │ Artist-painted layers can replace any of the 10 cloud        │
          │ placements. SVG is fallback when a placement has no PNG.     │
          └──────────────────────────────────────────────────────────────┘
          CLOUD blob — organic shape with multiple rounded lobes */}
      <symbol id="rh-cloud" viewBox="0 0 220 70">
        <path
          d="M 20 50 Q 10 50, 10 38 Q 10 24, 28 22 Q 32 8, 56 10 Q 72 -2, 96 8 Q 112 0, 130 12 Q 152 4, 170 16 Q 196 12, 204 28 Q 216 30, 214 46 Q 220 56, 200 58 Q 180 62, 156 56 Q 132 64, 108 58 Q 80 62, 58 56 Q 32 60, 20 50 Z"
          fill="currentColor"
        />
      </symbol>

      {/* ┌── RASTERIZABLE ──────────────────────────────────────────────┐
          │ rh-palm → manifest keys background/palm-bg-{left|right}      │
          │ Both placements are background palms (faded + atmospheric    │
          │ blur via parent .rh-landscape-bg filter).                    │
          └──────────────────────────────────────────────────────────────┘
          PALM TREE — more detailed: trunk segments + 9 fronds */}
      <symbol id="rh-palm" viewBox="0 0 100 240">
        {/* trunk with segment rings */}
        <path d="M 50 240 Q 47 180, 52 120 Q 56 70, 50 30" stroke="currentColor" strokeWidth="5" fill="none" strokeLinecap="round" />
        {/* segment rings on trunk */}
        {[200, 170, 140, 110, 80, 55].map((y, i) => (
          <ellipse key={i} cx={50} cy={y} rx="5" ry="1.2" fill="currentColor" opacity="0.4" />
        ))}
        {/* fronds — 9 spreading from top */}
        <g transform="translate(50 30)" stroke="currentColor" strokeWidth="2.5" fill="none" strokeLinecap="round">
          <path d="M 0 0 Q -32 -6, -54 12 Q -46 8, -42 18" />
          <path d="M 0 0 Q -28 -22, -42 -42 Q -34 -34, -28 -36" />
          <path d="M 0 0 Q -10 -28, -18 -54 Q -12 -46, -6 -46" />
          <path d="M 0 0 Q 2 -32, -2 -58 Q 4 -50, 10 -52" />
          <path d="M 0 0 Q 18 -28, 28 -54 Q 22 -46, 28 -46" />
          <path d="M 0 0 Q 28 -22, 42 -42 Q 36 -34, 32 -36" />
          <path d="M 0 0 Q 34 -6, 54 12 Q 46 8, 42 18" />
          <path d="M 0 0 Q 22 8, 32 26 Q 26 22, 26 28" />
          <path d="M 0 0 Q -18 8, -28 26 Q -22 22, -22 28" />
        </g>
        {/* coconut cluster */}
        <circle cx="46" cy="32" r="2.2" fill="currentColor" opacity="0.7" />
        <circle cx="52" cy="33" r="2.2" fill="currentColor" opacity="0.7" />
        <circle cx="49" cy="36" r="2" fill="currentColor" opacity="0.55" />
      </symbol>

      {/* ┌── RASTERIZABLE ──────────────────────────────────────────────┐
          │ rh-bush → manifest keys foreground/bush-{1..5}               │
          │ Five foreground bushes lining the garden beds. Color tints   │
          │ via parent currentColor — survive in raster mode through     │
          │ CSS filter:hue-rotate().                                     │
          └──────────────────────────────────────────────────────────────┘
          BUSH */}
      <symbol id="rh-bush" viewBox="0 0 80 40">
        <ellipse cx="20" cy="30" rx="18" ry="14" fill="currentColor" />
        <ellipse cx="40" cy="22" rx="22" ry="18" fill="currentColor" />
        <ellipse cx="60" cy="30" rx="18" ry="14" fill="currentColor" />
      </symbol>

      {/* ┌── RASTERIZABLE ──────────────────────────────────────────────┐
          │ rh-hibiscus → manifest keys foreground/hibiscus-{1..5}       │
          │ Tiny flower accents (sub-cm details). 1600×960 PNG canvas    │
          │ gives the artist plenty of room to add brushwork even though │
          │ the rendered scale is small.                                 │
          └──────────────────────────────────────────────────────────────┘
          HIBISCUS flower */}
      <symbol id="rh-hibiscus" viewBox="0 0 12 12">
        <circle cx="6" cy="3.5" r="2.2" fill="#e6486b" />
        <circle cx="3" cy="7" r="2.2" fill="#e6486b" />
        <circle cx="9" cy="7" r="2.2" fill="#e6486b" />
        <circle cx="6" cy="9" r="2.2" fill="#e6486b" />
        <circle cx="6" cy="6" r="1" fill="#fcd45f" />
      </symbol>

      {/* ┌── RASTERIZABLE ──────────────────────────────────────────────┐
          │ rh-treeline → manifest keys sky/treeline-{far|near}          │
          │ The horizon-line tree silhouette strip. Two depth bands      │
          │ (far + near, slightly different opacity in SkyAtmosphere).   │
          └──────────────────────────────────────────────────────────────┘
          TREELINE */}
      <symbol id="rh-treeline" viewBox="0 0 800 30">
        <path d="M 0 30 L 0 18 Q 30 8, 60 16 T 130 14 T 200 18 T 280 12 T 360 18 T 440 14 T 520 16 T 600 12 T 680 16 T 760 14 L 800 18 L 800 30 Z" fill="currentColor" />
      </symbol>

      {/* ┌── SVG-ONLY ──────────────────────────────────────────────────┐
          │ rh-bird — DO NOT add a PNG override.                         │
          │ The bird symbol drives a CSS-animated wing flap (the M-curve │
          │ stretches between two stop frames in @keyframes rh-bird-fly).│
          │ A static raster would freeze the wing animation. If you want │
          │ painted birds, the right path is to author a sprite-sheet    │
          │ animation, which is a deeper refactor than this exporter     │
          │ supports.                                                    │
          └──────────────────────────────────────────────────────────────┘ */}
      <symbol id="rh-bird" viewBox="0 0 20 10">
        <path d="M 0 6 Q 4 0, 8 6 Q 12 0, 16 6" stroke="currentColor" strokeWidth="1.2" fill="none" strokeLinecap="round" />
      </symbol>

      {/* ┌── SVG-ONLY ──────────────────────────────────────────────────┐
          │ rh-leaf — DO NOT add a PNG override.                         │
          │ Used by FlyingLeaves (WeatherEffects.tsx) to instance dozens │
          │ of debris leaves that translate across the screen with       │
          │ per-leaf stagger + storm-driven duration. The eye reads      │
          │ "many distinct leaves drifting" — replacing each instance    │
          │ with the same painted PNG would lose that variation. Also    │
          │ used as ground-litter accents in Landscape.tsx where each    │
          │ leaf is tinted differently via inline `style.color`; PNG     │
          │ can't accept that tint.                                      │
          └──────────────────────────────────────────────────────────────┘ */}
      <symbol id="rh-leaf" viewBox="0 0 12 8">
        <path d="M 0 4 Q 6 -2, 12 4 Q 6 10, 0 4 Z" fill="currentColor" />
        <line x1="0" y1="4" x2="12" y2="4" stroke="rgba(0,0,0,0.3)" strokeWidth="0.4" />
      </symbol>

      {/* CONCRETE driveway — what's at 2703 Dobbin. Plain pour concrete
          with subtle aggregate speckle + faint expansion-joint shadow. */}
      <pattern id="rh-concrete" width="20" height="20" patternUnits="userSpaceOnUse">
        <rect width="20" height="20" fill="#9a9690" />
        {/* Subtle aggregate speckle — looks like real cast concrete */}
        <circle cx="3.5" cy="4.0" r="0.30" fill="rgba(0, 0, 0, 0.18)" />
        <circle cx="6.0" cy="9.5" r="0.22" fill="rgba(255, 255, 255, 0.18)" />
        <circle cx="11" cy="2.5" r="0.26" fill="rgba(0, 0, 0, 0.16)" />
        <circle cx="14.5" cy="7.0" r="0.20" fill="rgba(255, 255, 255, 0.15)" />
        <circle cx="17" cy="13" r="0.28" fill="rgba(0, 0, 0, 0.18)" />
        <circle cx="9" cy="15" r="0.22" fill="rgba(255, 255, 255, 0.13)" />
        <circle cx="2" cy="17.5" r="0.24" fill="rgba(0, 0, 0, 0.16)" />
        <circle cx="13" cy="18" r="0.18" fill="rgba(255, 255, 255, 0.14)" />
      </pattern>

      {/* ┌── RASTERIZABLE — OPT-IN ─────────────────────────────────────┐
          │ rh-oak → manifest keys foreground/oak-tree-{left|right|mid}  │
          │ Each placement currently has skip:true in the export script  │
          │ because the symbol below ALREADY embeds a separately-painted │
          │ canopy PNG (/images/tree-oak-canopy.png). Auto-generating    │
          │ baseline oak PNGs + adding them to the manifest would cover  │
          │ that canopy painting.                                         │
          │                                                              │
          │ TWO RASTERIZATION MODES coexist for oaks:                    │
          │  1. Sub-element mode (current): canopy <image> embedded      │
          │     INSIDE this symbol. SVG trunk + branches + moss render   │
          │     around it. Same canopy PNG used for all 3 placements.    │
          │  2. Whole-element mode (opt-in): each placement gets its own │
          │     full-tree PNG. Remove skip:true in export script ELEMENTS│
          │     and re-run; the artist can paint each oak individually.  │
          │                                                              │
          │ See public/images/scene/README.md "The oak opt-in" section.  │
          └──────────────────────────────────────────────────────────────┘
          OAK TREE — wide rounded canopy with Spanish moss draped from
          a few branches. The Florida inland landmark tree (32817 Orlando
          is oak country, not coastal palms). */}
      <symbol id="rh-oak" viewBox="0 0 200 240">
        {/* ── ROOT FLARE — characteristic widening where the trunk meets
            the ground. Real Florida oaks have this prominent buttress
            base that's the easiest cue to a viewer that this is a
            "real" tree, not a generic clip-art tree. */}
        <ellipse cx="100" cy="238" rx="22" ry="6" fill="currentColor" opacity="0.55" />
        <path
          d="M 78 240 Q 82 230 90 224 L 110 224 Q 118 230 122 240 Z"
          fill="currentColor"
          opacity="0.85"
        />
        {/* Root-flare ridges (sun-catch on left side, shadow on right) */}
        <line x1="84" y1="234" x2="90" y2="226" stroke="rgba(255, 240, 200, 0.25)" strokeWidth="0.6" />
        <line x1="116" y1="234" x2="110" y2="226" stroke="rgba(0, 0, 0, 0.35)" strokeWidth="0.6" />

        {/* ── TAPERED TRUNK — properly tapered shape (wider at base,
            narrower toward the canopy) instead of a constant-width
            stroke. Path closes a quadrilateral that bows slightly
            for organic feel. */}
        <path
          d="M 90 224 Q 88 195 93 165 Q 96 130 96 100 L 104 100 Q 104 130 107 165 Q 112 195 110 224 Z"
          fill="currentColor"
          opacity="0.88"
        />
        {/* Sun-catch on the left (sun upper-left) */}
        <path
          d="M 90 224 Q 88 195 93 165 Q 96 130 96 100"
          stroke="rgba(255, 240, 200, 0.20)"
          strokeWidth="0.8"
          fill="none"
        />
        {/* Shadow on the right */}
        <path
          d="M 110 224 Q 112 195 107 165 Q 104 130 104 100"
          stroke="rgba(0, 0, 0, 0.45)"
          strokeWidth="0.8"
          fill="none"
        />

        {/* ── BARK TEXTURE — vertical fissures characteristic of
            mature southern live oak. Stack of dark fissure paths
            paired with thin lighter ridge highlights between them. */}
        <g stroke="rgba(0, 0, 0, 0.42)" strokeWidth="0.8" fill="none" strokeLinecap="round">
          <path d="M 95 220 Q 96 190 95 160 Q 94 130 95 105" />
          <path d="M 99 220 Q 100 190 99 160 Q 98 130 99 105" />
          <path d="M 103 220 Q 104 190 103 160 Q 102 130 103 105" />
        </g>
        {/* Ridge highlights between fissures (sun catches the high
            points of the bark) */}
        <g stroke="rgba(255, 235, 195, 0.22)" strokeWidth="0.4" fill="none" strokeLinecap="round">
          <path d="M 97 220 Q 98 190 97 160 Q 96 130 97 105" />
          <path d="M 101 220 Q 102 190 101 160 Q 100 130 101 105" />
        </g>
        {/* Knot — characteristic dark oval scar from a long-fallen
            branch. Adds the "this tree has lived through hurricanes
            before" character. */}
        <ellipse cx="103" cy="178" rx="3" ry="4" fill="rgba(0, 0, 0, 0.55)" />
        <ellipse cx="103" cy="178" rx="2" ry="3" fill="rgba(40, 28, 20, 0.85)" />
        <ellipse cx="102.4" cy="177.5" rx="0.8" ry="1.2" fill="rgba(255, 235, 195, 0.18)" />

        {/* ── BRANCHES — major limbs forking from the upper trunk.
            Drawn as polygon shapes (wider at base, tapering to tips)
            instead of constant-width strokes. */}
        {/* Left major branch */}
        <path
          d="M 96 110 Q 80 95 50 78 Q 48 80 50 82 Q 80 99 96 114 Z"
          fill="currentColor"
          opacity="0.82"
        />
        {/* Right major branch */}
        <path
          d="M 104 110 Q 122 92 158 70 Q 160 72 158 74 Q 122 95 104 114 Z"
          fill="currentColor"
          opacity="0.82"
        />
        {/* Upper-left branch */}
        <path
          d="M 97 100 Q 92 75 78 45 Q 80 44 82 46 Q 96 75 100 100 Z"
          fill="currentColor"
          opacity="0.78"
        />
        {/* Upper-right branch */}
        <path
          d="M 103 100 Q 110 75 126 45 Q 128 46 126 48 Q 110 76 105 100 Z"
          fill="currentColor"
          opacity="0.78"
        />

        {/* ── SUB-BRANCHES — secondary branching that turns the canopy
            into a real tree. Real oaks have constant forking, not just
            primary branches going from trunk to leaves. */}
        <g stroke="currentColor" strokeWidth="2" fill="none" strokeLinecap="round" opacity="0.72">
          <path d="M 70 88 Q 60 78 48 60" />
          <path d="M 60 84 Q 52 72 42 64" />
          <path d="M 130 88 Q 140 78 152 60" />
          <path d="M 140 84 Q 148 72 158 64" />
          <path d="M 88 80 Q 84 60 78 48" />
          <path d="M 112 80 Q 116 60 122 48" />
        </g>
        <g stroke="currentColor" strokeWidth="1.2" fill="none" strokeLinecap="round" opacity="0.65">
          <path d="M 56 70 Q 48 64 38 56" />
          <path d="M 144 70 Q 152 64 162 56" />
          <path d="M 78 56 Q 70 50 62 44" />
          <path d="M 122 56 Q 130 50 138 44" />
        </g>

        {/* ── CANOPY FALLBACK — soft underlying tone that shows IF the
            PNG canopy fails to load (broken path, network error, etc).
            On its own it looks minimal; with the PNG layered on top it
            adds depth + plants the tree visually even where the PNG
            has transparent edges. The tinted base also lets the
            currentColor scene-mood adaptation continue to work — at
            calm wind the underlay is greener, at storm it shifts
            browner with the rest of the scene. */}
        <ellipse cx="100" cy="62" rx="84" ry="58" fill="currentColor" opacity="0.45" />

        {/* ── CANOPY (PNG) — photographic/illustrated overlay sourced
            from public/images/tree-oak-canopy.png (694×694 RGBA).
            The PNG has a small trunk at the bottom; we crop it off
            with `preserveAspectRatio="xMidYMin slice"` (anchor top-
            middle, scale to fully cover the box, slice the bottom)
            so only the leafy canopy shows. The SVG trunk + Spanish
            moss + ground shadow underneath own the trunk area.

            Bounding box (x=4, y=-2, w=192, h=128) sits over the
            canopy zone of the symbol's 200×240 viewBox. With the
            square 1:1 source image and a wider-than-tall box,
            slice mode scales to width=192 then crops the bottom
            ~33% (the trunk + spacing) from view.

            CSS class .rh-oak-canopy on the image controls the mood-
            shift filters (saturate/brightness/drop-shadow) so the
            raster matches the painted aesthetic of the rest of the
            scene.  */}
        <image
          className="rh-oak-canopy"
          href="/images/tree-oak-canopy.png"
          x="4"
          y="-2"
          width="192"
          height="128"
          preserveAspectRatio="xMidYMin slice"
        />

        {/* ── SPANISH MOSS — clumps with tufts at the top + dangling
            strands. Real Spanish moss hangs in 12-30" trailing
            clumps, not single straight lines. */}
        {/* Left side moss clumps */}
        <g>
          <ellipse cx="48" cy="82" rx="6" ry="3" fill="rgba(180, 175, 145, 0.55)" />
          <path d="M 45 84 Q 43 105 41 130 Q 40 145 43 152" stroke="rgba(180, 175, 145, 0.65)" strokeWidth="2.8" fill="none" strokeLinecap="round" />
          <path d="M 50 84 Q 49 110 51 138 Q 52 152 49 158" stroke="rgba(180, 175, 145, 0.50)" strokeWidth="2.2" fill="none" strokeLinecap="round" />
          <path d="M 53 84 Q 55 100 53 122" stroke="rgba(180, 175, 145, 0.40)" strokeWidth="1.6" fill="none" strokeLinecap="round" />
        </g>
        <g>
          <ellipse cx="68" cy="92" rx="5" ry="2.6" fill="rgba(180, 175, 145, 0.50)" />
          <path d="M 65 94 Q 63 120 66 150 Q 68 162 63 168" stroke="rgba(180, 175, 145, 0.55)" strokeWidth="2.4" fill="none" strokeLinecap="round" />
          <path d="M 71 94 Q 70 118 72 138" stroke="rgba(180, 175, 145, 0.42)" strokeWidth="1.8" fill="none" strokeLinecap="round" />
        </g>
        {/* Right side moss clumps (mirrored) */}
        <g>
          <ellipse cx="148" cy="80" rx="6" ry="3" fill="rgba(180, 175, 145, 0.55)" />
          <path d="M 145 82 Q 148 105 150 130 Q 152 142 149 150" stroke="rgba(180, 175, 145, 0.65)" strokeWidth="2.8" fill="none" strokeLinecap="round" />
          <path d="M 151 82 Q 153 110 154 138 Q 155 152 152 158" stroke="rgba(180, 175, 145, 0.50)" strokeWidth="2.2" fill="none" strokeLinecap="round" />
          <path d="M 144 82 Q 142 100 144 122" stroke="rgba(180, 175, 145, 0.40)" strokeWidth="1.6" fill="none" strokeLinecap="round" />
        </g>
        <g>
          <ellipse cx="160" cy="90" rx="5" ry="2.6" fill="rgba(180, 175, 145, 0.50)" />
          <path d="M 158 92 Q 158 118 162 148 Q 164 162 160 168" stroke="rgba(180, 175, 145, 0.55)" strokeWidth="2.4" fill="none" strokeLinecap="round" />
          <path d="M 163 92 Q 165 116 162 136" stroke="rgba(180, 175, 145, 0.42)" strokeWidth="1.8" fill="none" strokeLinecap="round" />
        </g>
        {/* Center moss strands (between canopy ellipses) */}
        <path d="M 95 52 Q 93 80 91 105 Q 90 116 92 122" stroke="rgba(180, 175, 145, 0.42)" strokeWidth="1.8" fill="none" strokeLinecap="round" />
        <path d="M 120 56 Q 122 85 125 110 Q 126 120 124 126" stroke="rgba(180, 175, 145, 0.42)" strokeWidth="1.8" fill="none" strokeLinecap="round" />

        {/* ── GROUND-CONTACT SHADOW — subtle dark spot where the trunk
            meets the ground. Sells the tree as planted, not floating. */}
        <ellipse cx="100" cy="240" rx="28" ry="3" fill="rgba(0, 0, 0, 0.30)" />
      </symbol>

      {/* PAVER pattern for driveway/walkway — pushed 3D depth.
          Each paver now has: a top highlight (sun edge), left highlight,
          deep right + bottom joint shadows (recessed grout), AND inner
          subtle stone-grain flecks. Reads as cast concrete pavers with
          actual recessed mortar joints rather than flat tile. */}
      <pattern id="rh-pavers" width="14" height="10" patternUnits="userSpaceOnUse">
        {/* Base paver fill (warm grey) */}
        <rect width="14" height="10" fill="#7e7669" />
        {/* Subtle inner gradient — top of each paver lighter (sun) */}
        <rect width="7" height="3" fill="rgba(255, 248, 230, 0.06)" />
        <rect x="7" width="7" height="3" fill="rgba(255, 248, 230, 0.06)" />
        {/* Joint shadows — RIGHT + BOTTOM (sun upper-left = recess catches dark) */}
        <line x1="7" y1="0" x2="7" y2="10" stroke="#3a3024" strokeWidth="0.7" />
        <line x1="14" y1="0" x2="14" y2="10" stroke="#3a3024" strokeWidth="0.7" />
        <line x1="0" y1="10" x2="14" y2="10" stroke="#3a3024" strokeWidth="0.7" />
        <line x1="0" y1="0" x2="14" y2="0" stroke="#3a3024" strokeWidth="0.5" />
        {/* Joint highlight — LEFT + TOP edges of each paver catch sun */}
        <line x1="0" y1="0.4" x2="14" y2="0.4" stroke="rgba(255, 240, 210, 0.18)" strokeWidth="0.3" />
        <line x1="0" y1="0" x2="0" y2="10" stroke="rgba(255, 240, 210, 0.10)" strokeWidth="0.3" />
        <line x1="7.4" y1="0" x2="7.4" y2="10" stroke="rgba(255, 240, 210, 0.08)" strokeWidth="0.3" />
        {/* Stone-grain flecks (varied per paver for non-repeating feel) */}
        <circle cx="2.0" cy="3.0" r="0.20" fill="rgba(255,255,255,0.07)" />
        <circle cx="5.2" cy="6.2" r="0.18" fill="rgba(0,0,0,0.20)" />
        <circle cx="3.5" cy="8.0" r="0.22" fill="rgba(255,255,255,0.06)" />
        <circle cx="9.4" cy="2.4" r="0.20" fill="rgba(0,0,0,0.18)" />
        <circle cx="11.5" cy="5.5" r="0.18" fill="rgba(255,255,255,0.07)" />
        <circle cx="10.0" cy="7.8" r="0.22" fill="rgba(0,0,0,0.16)" />
      </pattern>

      {/* MULCH */}
      <pattern id="rh-mulch" width="6" height="6" patternUnits="userSpaceOnUse">
        <rect width="6" height="6" fill="#5a3820" />
        <circle cx="1" cy="1" r="0.6" fill="#7a4f2a" />
        <circle cx="4" cy="3" r="0.7" fill="#3e2818" />
        <circle cx="2" cy="5" r="0.5" fill="#7a4f2a" />
      </pattern>

      <pattern id="rh-rain" x="0" y="0" width="14" height="22" patternUnits="userSpaceOnUse" patternTransform={`rotate(${15 + storm * 10})`}>
        <line x1="0" y1="0" x2="0" y2="14" stroke="#a8c8e0" strokeWidth="0.7" strokeOpacity="0.8" />
      </pattern>

      <pattern id="rh-grass" x="0" y="0" width="6" height="3" patternUnits="userSpaceOnUse">
        <line x1="0" y1="3" x2="2" y2="0" stroke="rgba(0,0,0,0.25)" strokeWidth="0.4" />
        <line x1="3" y1="3" x2="5" y2="0" stroke="rgba(0,0,0,0.18)" strokeWidth="0.4" />
      </pattern>

      <linearGradient id="rh-lawn" x1="0" y1="0" x2="0" y2="1">
        <stop offset="0%" stopColor={lawnTop} />
        <stop offset="100%" stopColor={lawnBot} />
      </linearGradient>

      {/* CAD blueprint grid (kept) */}
      <pattern id="rh-blueprint" x="0" y="0" width="20" height="20" patternUnits="userSpaceOnUse">
        <path d="M 20 0 L 0 0 0 20" fill="none" stroke="rgba(255,255,255,0.04)" strokeWidth="0.5" />
      </pattern>
      <pattern id="rh-blueprint-major" x="0" y="0" width="100" height="100" patternUnits="userSpaceOnUse">
        <path d="M 100 0 L 0 0 0 100" fill="none" stroke="rgba(255,255,255,0.08)" strokeWidth="0.6" />
      </pattern>

      <marker id="rh-arrow" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse">
        <path d="M 0 0 L 10 5 L 0 10 z" fill="#f5894d" />
      </marker>

      <filter id="rh-glow"><feGaussianBlur stdDeviation="3" result="b" /><feMerge><feMergeNode in="b" /><feMergeNode in="SourceGraphic" /></feMerge></filter>
      <filter id="rh-bolt-glow" x="-50%" y="-50%" width="200%" height="200%"><feGaussianBlur stdDeviation="3" /></filter>

      {/* COLOR-GRADE CORNER VIGNETTE — radial gradient used by the
          final color-grade overlay at extreme storm. Crushes the
          corners deep navy for vibrant lows. Wider radius than the
          base vignette so it stacks rather than competes. */}
      <radialGradient id="rh-grade-vignette" cx="50%" cy="55%" r="78%">
        <stop offset="55%" stopColor="rgba(0, 0, 0, 0)" />
        <stop offset="100%" stopColor="rgba(8, 12, 28, 0.85)" />
      </radialGradient>

      {/* CREPUSCULAR RAY — bright shaft of light fanning down through
          a gap in the clouds. Linear gradient that fades from a hot
          warm-white at the top to nothing at the bottom. Used at
          moderate storm with sun visible. */}
      <linearGradient id="rh-crepuscular-ray" x1="0.5" y1="0" x2="0.5" y2="1">
        <stop offset="0%" stopColor="rgba(255, 240, 200, 0.45)" />
        <stop offset="60%" stopColor="rgba(255, 230, 175, 0.18)" />
        <stop offset="100%" stopColor="rgba(255, 220, 160, 0)" />
      </linearGradient>

      {/* PROCEDURAL ATMOSPHERIC TURBULENCE — real GPU-accelerated SVG
          fractal-noise. Used by <AtmosphericTurbulence> as a single
          drift-translated layer over the sky during storm. Equivalent to
          a fragment shader's `noise()` call but native to SVG (no WebGL).
          stitchTiles="stitch" → seamless loop when translated by integer
          multiples of (1/baseFrequency_x). With baseFrequency_x=0.015,
          the wavelength is ~66.67px → translate by 200px (3 cycles)
          for a seamless-feeling loop. */}
      <filter id="rh-air-turb" x="-10%" y="0%" width="120%" height="100%">
        <feTurbulence
          type="fractalNoise"
          /* Lower frequency = larger softer blobs, reads as drifting
             clouds/haze rather than noise grain. Was 0.015/0.030. */
          baseFrequency="0.009 0.018"
          numOctaves="2"
          seed="3"
          stitchTiles="stitch"
        />
        {/* Push the noise toward cool atmospheric blue-grey + reduce
            alpha so the layer feels like volumetric haze, not noise */}
        <feColorMatrix values="
          0.55 0.55 0.55 0 0
          0.62 0.62 0.62 0 0
          0.74 0.74 0.74 0 0
          0    0    0    0.55 0
        " />
      </filter>
    </defs>
  );
}
