import { useMemo, type ReactNode } from 'react';
import './Testimonials.css';
import {
  REVIEWS,
  buildAggregateRating,
  type ReviewEntry,
} from '../data/reviews';

/**
 * Testimonials section — sources real customer reviews from
 * src/data/reviews.ts.
 *
 * The data file is the single source of truth: it drives this visible
 * UI block AND the AggregateRating + Review JSON-LD schema generated by
 * src/data/schemas/reviews.ts. Editing reviews here would be a no-op —
 * always edit src/data/reviews.ts.
 *
 * Re-use across pages:
 *   <Testimonials /> — uses the full REVIEWS list and default heading.
 *   <Testimonials reviews={cityReviews} ... /> — used by city pages
 *     (Phase 6+) to render a filtered subset.
 *
 * If/when the owner provides real datePublished + sourcePlatform per
 * review (Phase 12 — Google Business Profile integration), the schema
 * automatically picks them up; this UI can also surface a verification
 * badge ("Verified Google review") at that point.
 */
export interface TestimonialsProps {
  /** Reviews to render. Defaults to the full REVIEWS list. */
  reviews?: ReviewEntry[];
  /** Override eyebrow label above the heading. */
  eyebrow?: string;
  /** Override heading content (pass JSX for the italic em accent). */
  titleNode?: ReactNode;
}

/** Compose the displayed attribution row: "Homeowner · Orlando, FL" */
function attribution(role?: string, location?: string): string {
  const parts: string[] = [];
  if (role) parts.push(role);
  if (location) parts.push(location);
  return parts.join(' · ');
}

/** Derive 2-letter avatar initials when not explicitly provided. */
function initialsFor(author: string, override?: string): string {
  if (override) return override;
  const tokens = author.trim().split(/\s+/);
  if (tokens.length === 1) return tokens[0].slice(0, 2).toUpperCase();
  return (tokens[0][0] + tokens[tokens.length - 1][0]).toUpperCase();
}

function Stars({ rating = 5 }: { rating?: number }) {
  // Round to nearest int — UI shows whole stars only, schema preserves
  // the precise rating.
  const filled = Math.max(0, Math.min(5, Math.round(rating)));
  return (
    <span className="testimonial__stars" aria-label={`${filled} out of 5 stars`}>
      {Array.from({ length: 5 }).map((_, i) => (
        <svg key={i} viewBox="0 0 20 20" aria-hidden="true" data-filled={i < filled}>
          <path d="M10 1.5l2.6 5.27 5.82.85-4.21 4.1.99 5.78L10 14.77 4.8 17.5l.99-5.78L1.58 7.62l5.82-.85L10 1.5z" />
        </svg>
      ))}
    </span>
  );
}

/** Map verifiedBadge value to a display label + a tooltip-friendly hint. */
function verifiedLabel(source: NonNullable<ReviewEntry['verifiedBadge']>): string {
  switch (source) {
    case 'google': return 'Verified Google review';
    case 'facebook': return 'Verified Facebook review';
    case 'bbb': return 'Verified BBB review';
  }
}

const CheckIcon = () => (
  <svg viewBox="0 0 20 20" width="11" height="11" aria-hidden="true" fill="none" stroke="currentColor" strokeWidth="2.6" strokeLinecap="round" strokeLinejoin="round">
    <polyline points="5 10 9 14 15 6" />
  </svg>
);

export default function Testimonials({
  reviews,
  eyebrow,
  titleNode,
}: TestimonialsProps = {}) {
  const items = useMemo(() => reviews ?? REVIEWS, [reviews]);
  // Aggregate is computed from the visible review list so per-city pages
  // show the rating that reflects only the reviews actually on the page.
  const aggregate = useMemo(() => buildAggregateRating(items), [items]);
  const headingEyebrow = eyebrow ?? 'What Our Clients Say';
  const heading = titleNode ?? (
    <>
      Client <em>Testimonials</em>
    </>
  );
  return (
    <section
      className="testimonials section section--dark"
      aria-label="Client testimonials"
      // ARIA-describing the rating helps screen readers + Google parse
      // the page rating with the schema's AggregateRating consistently.
      aria-describedby="testimonials-rating"
    >
      <div className="container">
        <header className="testimonials__header reveal">
          <p className="eyebrow">{headingEyebrow}</p>
          <h2 className="testimonials__title">{heading}</h2>
          {aggregate.reviewCount > 0 && (
            <p
              id="testimonials-rating"
              className="testimonials__aggregate"
              aria-label={`${aggregate.ratingValue.toFixed(1)} average from ${aggregate.reviewCount} review${aggregate.reviewCount === 1 ? '' : 's'}`}
            >
              <span
                className="testimonials__aggregate-stars"
                aria-hidden="true"
              >
                <Stars rating={aggregate.ratingValue} />
              </span>
              <span className="testimonials__aggregate-text">
                <strong>{aggregate.ratingValue.toFixed(1)}</strong>
                <span>
                  {' from '}
                  {aggregate.reviewCount}{' '}
                  {aggregate.reviewCount === 1 ? 'review' : 'reviews'}
                </span>
              </span>
            </p>
          )}
        </header>

        <ul className="testimonials__list">
          {items.map((r) => (
            <li key={r.id} className="testimonial reveal">
              {/* Project-type tag — appears at top of card when the
                  reviewed project is categorised. Lets visitors quickly
                  see "this person had X done" before reading the quote. */}
              {r.projectType && (
                <span className="testimonial__project-tag">{r.projectType}</span>
              )}
              <Stars rating={r.rating ?? 5} />
              <blockquote className="testimonial__quote">{r.quote}</blockquote>
              <footer className="testimonial__attr">
                {/* Avatar — real photo if provided, fallback to initials.
                    Photos require explicit customer approval for marketing
                    use; until then, initials are the safe default. */}
                {r.photoUrl ? (
                  <img
                    src={r.photoUrl}
                    alt={`${r.author} profile photo`}
                    className="testimonial__avatar testimonial__avatar--photo"
                    width={44}
                    height={44}
                    loading="lazy"
                  />
                ) : (
                  <span className="testimonial__avatar" aria-hidden="true">
                    {initialsFor(r.author, r.initials)}
                  </span>
                )}
                <span className="testimonial__who">
                  <strong className="testimonial__author">{r.author}</strong>
                  <span className="testimonial__role">
                    {attribution(r.role, r.location)}
                  </span>
                  {/* Verified-source pill — strongest trust signal when
                      sourceUrl is also set (linking to the live profile). */}
                  {r.verifiedBadge && (
                    <span
                      className={`testimonial__verified testimonial__verified--${r.verifiedBadge}`}
                      title={verifiedLabel(r.verifiedBadge)}
                    >
                      <CheckIcon />
                      <span>{verifiedLabel(r.verifiedBadge)}</span>
                    </span>
                  )}
                </span>
              </footer>
            </li>
          ))}
        </ul>
      </div>
    </section>
  );
}
