/**
 * Scene raster manifest — AUTO-GENERATED by scripts/export-scene-elements.mjs.
 * Lists every PNG present in public/images/scene/, grouped by category.
 * The visualizer's <SceneElement> component checks this manifest to decide
 * whether to render an artist-painted PNG layer or fall back to the SVG.
 *
 * DO NOT EDIT BY HAND — re-run `node scripts/export-scene-elements.mjs`.
 */
export interface SceneRasterEntry {
  category: string;
  name: string;
  /** URL the runtime fetches from public/images/scene/ */
  href: string;
}

export const SCENE_RASTER_INDEX: Record<string, SceneRasterEntry> = {
  "background/palm-bg-left": {
    "category": "background",
    "name": "palm-bg-left",
    "href": "/images/scene/background/palm-bg-left.png"
  },
  "background/palm-bg-right": {
    "category": "background",
    "name": "palm-bg-right",
    "href": "/images/scene/background/palm-bg-right.png"
  },
  "foreground/bush-1": {
    "category": "foreground",
    "name": "bush-1",
    "href": "/images/scene/foreground/bush-1.png"
  },
  "foreground/bush-2": {
    "category": "foreground",
    "name": "bush-2",
    "href": "/images/scene/foreground/bush-2.png"
  },
  "foreground/bush-3": {
    "category": "foreground",
    "name": "bush-3",
    "href": "/images/scene/foreground/bush-3.png"
  },
  "foreground/bush-4": {
    "category": "foreground",
    "name": "bush-4",
    "href": "/images/scene/foreground/bush-4.png"
  },
  "foreground/bush-5": {
    "category": "foreground",
    "name": "bush-5",
    "href": "/images/scene/foreground/bush-5.png"
  },
  "foreground/hibiscus-1": {
    "category": "foreground",
    "name": "hibiscus-1",
    "href": "/images/scene/foreground/hibiscus-1.png"
  },
  "foreground/hibiscus-2": {
    "category": "foreground",
    "name": "hibiscus-2",
    "href": "/images/scene/foreground/hibiscus-2.png"
  },
  "foreground/hibiscus-3": {
    "category": "foreground",
    "name": "hibiscus-3",
    "href": "/images/scene/foreground/hibiscus-3.png"
  },
  "foreground/hibiscus-4": {
    "category": "foreground",
    "name": "hibiscus-4",
    "href": "/images/scene/foreground/hibiscus-4.png"
  },
  "foreground/hibiscus-5": {
    "category": "foreground",
    "name": "hibiscus-5",
    "href": "/images/scene/foreground/hibiscus-5.png"
  },
  "sky/cloud-bg-1": {
    "category": "sky",
    "name": "cloud-bg-1",
    "href": "/images/scene/sky/cloud-bg-1.png"
  },
  "sky/cloud-bg-2": {
    "category": "sky",
    "name": "cloud-bg-2",
    "href": "/images/scene/sky/cloud-bg-2.png"
  },
  "sky/cloud-bg-3": {
    "category": "sky",
    "name": "cloud-bg-3",
    "href": "/images/scene/sky/cloud-bg-3.png"
  },
  "sky/cloud-bg-4": {
    "category": "sky",
    "name": "cloud-bg-4",
    "href": "/images/scene/sky/cloud-bg-4.png"
  },
  "sky/cloud-mid-1": {
    "category": "sky",
    "name": "cloud-mid-1",
    "href": "/images/scene/sky/cloud-mid-1.png"
  },
  "sky/cloud-mid-2": {
    "category": "sky",
    "name": "cloud-mid-2",
    "href": "/images/scene/sky/cloud-mid-2.png"
  },
  "sky/cloud-mid-3": {
    "category": "sky",
    "name": "cloud-mid-3",
    "href": "/images/scene/sky/cloud-mid-3.png"
  },
  "sky/cloud-near-1": {
    "category": "sky",
    "name": "cloud-near-1",
    "href": "/images/scene/sky/cloud-near-1.png"
  },
  "sky/cloud-near-2": {
    "category": "sky",
    "name": "cloud-near-2",
    "href": "/images/scene/sky/cloud-near-2.png"
  },
  "sky/cloud-near-3": {
    "category": "sky",
    "name": "cloud-near-3",
    "href": "/images/scene/sky/cloud-near-3.png"
  },
  "sky/treeline-far": {
    "category": "sky",
    "name": "treeline-far",
    "href": "/images/scene/sky/treeline-far.png"
  },
  "sky/treeline-near": {
    "category": "sky",
    "name": "treeline-near",
    "href": "/images/scene/sky/treeline-near.png"
  }
};

/** Convenience helper — true when the named element has a painted PNG. */
export function hasRaster(category: string, name: string): boolean {
  return Boolean(SCENE_RASTER_INDEX[`${category}/${name}`]);
}
